package com.bingbingbing.enchantment;

import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.item.enchantment.EnchantmentCategory;

/**
 * A cosmetic "bingbingbing" enchantment.
 * - Never generated by the enchanting table, loot, fishing or villager trades (isDiscoverable = false).
 * - Applied only via the custom book in an anvil (handled in AnvilHandler, which bypasses cost/penalty).
 */
public class BingbingbingEnchantment extends Enchantment {

    public BingbingbingEnchantment(EnchantmentCategory category, EquipmentSlot[] slots) {
        super(Rarity.VERY_RARE, category, slots);
    }

    @Override
    public int getMaxLevel() {
        return 1;
    }

    @Override
    public int getMinLevel() {
        return 1;
    }

    // Keep it out of the enchanting table (and out of natural loot/trades).
    @Override
    public boolean isDiscoverable() {
        return false;
    }

    @Override
    public boolean isTradeable() {
        return false;
    }

    // Allowed to sit on our book item conceptually; actual application is done in the anvil handler.
    @Override
    public boolean isAllowedOnBooks() {
        return true;
    }
}
